version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: Setup Dependencies
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test